Soporte/Controllers/RolController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using Soporte.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Soporte.Controllers
{
    public class RolController : Controller
    {
        ApplicationDbContext context;

        public RolController()
        {
            context = new ApplicationDbContext();
        }

        //

            [Authorize]
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }


        // GET: Rol/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Rol/Create
     //   [Authorize(Roles ="ADMINISTRADOR")]
        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }
        // POST: Rol/Create
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            try
            {
                if (User.IsInRole("ADMINISTRADOR"))
                {
                    context.Roles.Add(Role);
                    context.SaveChanges();
                   
                }
                else {
                    ViewBag.Error = "No Posee autorizacion";
                    return View(Role);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Rol/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Rol/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Rol/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Rol/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Soporte/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                  
                </ul>



                @*@if (User.Identity.IsAuthenticated)
                {

                    if (User.IsInRole("ADMINISTRADOR"))
                    {*@
                        <li class="dropdown">

                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">MODIFICACIONES <b class="caret"></b></a>
                            <ul role="menu" class="dropdown-menu">
                                <li>@Html.ActionLink("Cliente", "Index", "Cliente")</li> 
                                <li><a href="#">@Html.ActionLink("ROL", "Index", "Rol")</a></li>

                                <li class="divider"></li>
                                <li><a href="#">@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</a></li>
                            </ul>
                        </li>
                    @*}
                }*@



                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>